name: min build

on:
  push:
    paths:
      - 'jsstp.js'
  workflow_dispatch:

jobs:
  update:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: disable auto crlf
        uses: steve02081504/disable-autocrlf@v1
        with:
          fuck-auto-CRLF: true
      - uses: actions/checkout@v2

      - name: Minify
        run: |
          npm install uglify-js -g
          uglifyjs ./jsstp.js -o ./jsstp.min.js -c "pure_funcs=['console.info','console.error'],unsafe=true" -m --mangle-props regex=/^#/
          rm -rf ./jsstp.mjs
          echo -n "export " > jsstp.mjs && cat jsstp.min.js >> jsstp.mjs

      - name: add all
        run: git add -A
      - name: push
        uses: actions-go/push@master
        with:
          author-email: taromati2@outlook.com
          author-name: Taromati2
          commit-message: 'file update~'
          remote: origin
